#!/usr/bin/env python3
"""Download missing flag PNGs for all DB countries and regenerate availableFlags.js."""

from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
FLAGS_DIR = ROOT / "frontend" / "public" / "flags"
SQL = ROOT / "data/schema/import_data_only.sql"
GEO = ROOT / "frontend/src/config/countryGeography.js"
ISO3_JS = ROOT / "frontend/src/utils/iso3ToIso2.js"
AVAILABLE_FLAGS_JS = ROOT / "frontend/src/utils/availableFlags.js"
NORMALIZE = ROOT / "scripts/normalize_flag.py"

# 世行 Excel 未包含、由补充脚本写入数据库的历史实体
SUPPLEMENTAL_DB_CODES = {"SUN", "TWN"}

# ISO3 -> ISO2 copied from frontend mapping (keep in sync)
ISO3_TO_ISO2 = {
    "ABW": "aw", "AFG": "af", "AGO": "ao", "ALB": "al", "AND": "ad", "ARE": "ae",
    "ARG": "ar", "ARM": "am", "ASM": "as", "ATG": "ag", "AUS": "au", "AUT": "at",
    "AZE": "az", "BDI": "bi", "BEL": "be", "BEN": "bj", "BFA": "bf", "BGD": "bd",
    "BGR": "bg", "BHR": "bh", "BHS": "bs", "BIH": "ba", "BLR": "by", "BLZ": "bz",
    "BOL": "bo", "BRA": "br", "BRB": "bb", "BRN": "bn", "BTN": "bt", "BWA": "bw",
    "CAF": "cf", "CAN": "ca", "CHE": "ch", "CHL": "cl", "CHN": "cn", "CIV": "ci",
    "CMR": "cm", "COD": "cd", "COG": "cg", "COL": "co", "COM": "km", "CPV": "cv",
    "CRI": "cr", "CUB": "cu", "CUW": "cw", "CYM": "ky", "CYP": "cy", "CZE": "cz",
    "DEU": "de", "DJI": "dj", "DMA": "dm", "DNK": "dk", "DOM": "do", "DZA": "dz",
    "ECU": "ec", "EGY": "eg", "ERI": "er", "ESP": "es", "EST": "ee", "ETH": "et",
    "FIN": "fi", "FJI": "fj", "FRA": "fr", "FRO": "fo", "FSM": "fm", "GAB": "ga",
    "GBR": "gb", "GEO": "ge", "GHA": "gh", "GIB": "gi", "GIN": "gn", "GMB": "gm",
    "GNB": "gw", "GNQ": "gq", "GRC": "gr", "GRD": "gd", "GRL": "gl", "GTM": "gt",
    "GUM": "gu", "GUY": "gy", "HKG": "hk", "HND": "hn", "HRV": "hr", "HTI": "ht",
    "HUN": "hu", "IDN": "id", "IMN": "im", "IND": "in", "IRL": "ie", "IRN": "ir",
    "IRQ": "iq", "ISL": "is", "ISR": "il", "ITA": "it", "JAM": "jm", "JOR": "jo",
    "JPN": "jp", "KAZ": "kz", "KEN": "ke", "KGZ": "kg", "KHM": "kh", "KIR": "ki",
    "KNA": "kn", "KOR": "kr", "KWT": "kw", "LAO": "la", "LBN": "lb", "LBR": "lr",
    "LBY": "ly", "LCA": "lc", "LIE": "li", "LKA": "lk", "LSO": "ls", "LTU": "lt",
    "LUX": "lu", "LVA": "lv", "MAC": "mo", "MAF": "mf", "MAR": "ma", "MCO": "mc",
    "MDA": "md", "MDG": "mg", "MDV": "mv", "MEX": "mx", "MHL": "mh", "MKD": "mk",
    "MLI": "ml", "MLT": "mt", "MMR": "mm", "MNE": "me", "MNG": "mn", "MNP": "mp",
    "MOZ": "mz", "MRT": "mr", "MUS": "mu", "MWI": "mw", "MYS": "my", "NAM": "na",
    "NCL": "nc", "NER": "ne", "NGA": "ng", "NIC": "ni", "NLD": "nl", "NOR": "no",
    "NPL": "np", "NRU": "nr", "NZL": "nz", "OMN": "om", "PAK": "pk", "PAN": "pa",
    "PER": "pe", "PHL": "ph", "PLW": "pw", "PNG": "pg", "POL": "pl", "PRI": "pr",
    "PRK": "kp", "PRT": "pt", "PRY": "py", "PSE": "ps", "PYF": "pf", "QAT": "qa",
    "ROU": "ro", "RUS": "ru", "RWA": "rw", "SAU": "sa", "SDN": "sd", "SEN": "sn",
    "SGP": "sg", "SLB": "sb", "SLE": "sl", "SLV": "sv", "SMR": "sm", "SOM": "so",
    "SRB": "rs", "SSD": "ss", "STP": "st", "SUR": "sr", "SVK": "sk", "SVN": "si",
    "SUN": "su", "SWE": "se", "SWZ": "sz", "SXM": "sx", "SYC": "sc", "SYR": "sy",
    "TCA": "tc", "TCD": "td", "TGO": "tg", "THA": "th", "TJK": "tj", "TKM": "tm",
    "TLS": "tl", "TON": "to", "TTO": "tt", "TUN": "tn", "TUR": "tr", "TUV": "tv",
    "TWN": "tw", "TZA": "tz", "UGA": "ug", "UKR": "ua", "URY": "uy", "USA": "us",
    "UZB": "uz", "VCT": "vc", "VEN": "ve", "VGB": "vg", "VIR": "vi", "VNM": "vn",
    "VUT": "vu", "WSM": "ws", "XKX": "xk", "YEM": "ye", "ZAF": "za", "ZMB": "zm",
    "ZWE": "zw",
    "CHI": "gg",
    "BMU": "bm",
}


def load_db_iso3() -> set[str]:
    content = SQL.read_text(encoding="utf-8")
    pat = re.compile(r"\('[\d]+', '([A-Z]{3})', '((?:[^']|'')*)', '([^']*)',")
    codes = {m.group(1) for m in pat.finditer(content) if m.group(3)}
    return codes | SUPPLEMENTAL_DB_CODES


def iso3_to_iso2(iso3: str) -> str:
    code = iso3.upper()
    return ISO3_TO_ISO2.get(code, code[:2].lower())


def required_iso2_codes() -> set[str]:
    return {iso3_to_iso2(code) for code in load_db_iso3()}


def existing_iso2_codes() -> set[str]:
    return {p.stem for p in FLAGS_DIR.glob("*.png")}


def write_available_flags_js(codes: set[str]) -> None:
    ordered = sorted(codes)
    lines = [
        "/** Auto-generated by scripts/download_missing_flags.py — do not edit by hand. */",
        "",
        "export const AVAILABLE_FLAG_ISO2 = new Set([",
    ]
    chunk = []
    for code in ordered:
        chunk.append(f"'{code}'")
        if len(chunk) == 12:
            lines.append("  " + ", ".join(chunk) + ",")
            chunk = []
    if chunk:
        lines.append("  " + ", ".join(chunk))
    lines.append("])")
    lines.append("")
    lines.append("export function getFlagUrl(iso2) {")
    lines.append("  if (!iso2 || !AVAILABLE_FLAG_ISO2.has(iso2)) {")
    lines.append("    return null")
    lines.append("  }")
    lines.append("  return `/flags/${iso2}.png`")
    lines.append("}")
    lines.append("")
    AVAILABLE_FLAGS_JS.write_text("\n".join(lines), encoding="utf-8")


def download_code(code: str) -> bool:
    dest = FLAGS_DIR / f"{code}.png"
    dest.parent.mkdir(parents=True, exist_ok=True)
    if not dest.exists():
        dest.touch()
    result = subprocess.run(
        [sys.executable, str(NORMALIZE), code, "--refresh"],
        cwd=ROOT,
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        print(result.stdout)
        print(result.stderr, file=sys.stderr)
        return False
    print(result.stdout.strip())
    return dest.exists() and dest.stat().st_size > 200


def main() -> None:
    required = required_iso2_codes()
    existing = existing_iso2_codes()
    missing = sorted(required - existing)

    print(f"Required: {len(required)}, existing: {len(existing)}, missing: {len(missing)}")
    if missing:
        print("Missing:", ", ".join(missing))

    failed: list[str] = []
    for code in missing:
        print(f"\n==> {code}")
        if not download_code(code):
            failed.append(code)
            if dest := FLAGS_DIR / f"{code}.png":
                if dest.exists() and dest.stat().st_size <= 200:
                    dest.unlink(missing_ok=True)

    # Re-normalize existing flags that were already present (optional skip)
    all_codes = sorted(required - set(failed))
    for code in sorted(existing & required):
        all_codes_set = set(all_codes)
        if code in all_codes_set:
            continue

    final_codes = existing_iso2_codes() & required
    # 历史实体国旗（如苏联 su）即使数据库尚未导入也保留
    for extra in ("su", "tw"):
        if (FLAGS_DIR / f"{extra}.png").exists():
            final_codes.add(extra)
    write_available_flags_js(final_codes)
    print(f"\nWrote {AVAILABLE_FLAGS_JS} with {len(final_codes)} flags")

    if failed:
        print(f"\nFailed ({len(failed)}): {', '.join(failed)}")
        raise SystemExit(1)


if __name__ == "__main__":
    main()
