#!/usr/bin/env python3
"""Generate frontend/src/config/countryGeography.js from geographic rules."""

from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SQL = ROOT / "data/schema/import_data_only.sql"
OUT = ROOT / "frontend/src/config/countryGeography.js"

# 世行 Excel 未包含、由补充脚本写入数据库的历史实体
SUPPLEMENTAL_DB_CODES = {"SUN", "TWN"}

GEOGRAPHY = {
    "asia": {
        "eastAsia": [
            "CHN", "JPN", "KOR", "PRK", "MNG", "HKG", "MAC", "TWN",
        ],
        "southeastAsia": [
            "IDN", "THA", "MYS", "SGP", "VNM", "PHL", "MMR", "KHM", "LAO", "BRN", "TLS",
        ],
        "southAsia": [
            "IND", "PAK", "BGD", "LKA", "NPL", "BTN", "MDV", "AFG",
        ],
        "westAsia": [
            "SAU", "ARE", "QAT", "KWT", "OMN", "BHR", "ISR", "JOR", "LBN", "IRQ", "IRN",
            "SYR", "YEM", "TUR", "PSE",
        ],
        "centralAsia": ["KAZ", "UZB", "TKM", "KGZ", "TJK"],
        "caucasus": ["ARM", "AZE", "GEO"],
    },
    "europe": {
        "northernEurope": [
            "DNK", "EST", "FIN", "ISL", "LTU", "LVA", "NOR", "SWE", "FRO", "IMN",
        ],
        "westernEurope": [
            "AUT", "BEL", "CHE", "DEU", "FRA", "GBR", "IRL", "LUX", "NLD", "LIE", "MCO",
            "AND", "SMR", "GIB", "CHI",
        ],
        "southernEurope": [
            "GRC", "ITA", "ESP", "PRT", "HRV", "SVN", "MKD", "ALB", "MLT", "BIH", "MNE",
            "SRB", "XKX", "CYP",
        ],
        "easternEurope": [
            "POL", "CZE", "SVK", "HUN", "ROU", "BGR", "UKR", "BLR", "RUS", "MDA", "SUN",
        ],
    },
    "africa": {
        "northAfrica": ["DZA", "EGY", "LBY", "MAR", "SDN", "TUN"],
        "westAfrica": [
            "BEN", "BFA", "CIV", "GHA", "GIN", "GMB", "GNB", "LBR", "MLI", "MRT", "NER",
            "NGA", "SEN", "SLE", "TGO", "CPV", "STP",
        ],
        "centralAfrica": ["AGO", "CMR", "CAF", "TCD", "COD", "COG", "GNQ", "GAB", "SSD"],
        "eastAfrica": [
            "BDI", "COM", "DJI", "ERI", "ETH", "KEN", "MDG", "MUS", "RWA", "SYC", "SOM",
            "TZA", "UGA",
        ],
        "southernAfrica": ["ZAF", "BWA", "NAM", "LSO", "SWZ", "ZMB", "ZWE", "MOZ", "MWI"],
    },
    "oceania": {
        "australasia": ["AUS", "NZL"],
        "melanesia": ["FJI", "PNG", "SLB", "VUT", "NCL"],
        "micronesia": ["FSM", "KIR", "MHL", "NRU", "PLW", "GUM", "MNP"],
        "polynesia": ["TON", "TUV", "WSM", "PYF", "ASM"],
    },
    "northAmerica": {
        "northernAmerica": ["USA", "CAN", "BMU", "GRL"],
        "centralAmerica": ["MEX", "GTM", "BLZ", "HND", "SLV", "NIC", "CRI", "PAN"],
        "caribbean": [
            "ABW", "ATG", "BHS", "BRB", "CUB", "CUW", "CYM", "DMA", "DOM", "GRD", "HTI",
            "JAM", "KNA", "LCA", "MAF", "PRI", "SXM", "TCA", "TTO", "VCT", "VGB", "VIR",
        ],
    },
    "southAmerica": {
        "northernSouthAmerica": ["COL", "VEN", "GUY", "SUR", "ECU", "PER", "BOL"],
        "southernSouthAmerica": ["ARG", "CHL", "URY", "PRY"],
        "brazil": ["BRA"],
    },
}


def load_db_codes() -> set[str]:
    content = SQL.read_text(encoding="utf-8")
    pat = re.compile(r"\('[\d]+', '([A-Z]{3})', '((?:[^']|'')*)', '([^']*)',")
    codes = {m.group(1) for m in pat.finditer(content) if m.group(3)}
    return codes | SUPPLEMENTAL_DB_CODES


def build_lookup() -> dict[str, dict[str, str]]:
    lookup: dict[str, dict[str, str]] = {}
    for continent, subregions in GEOGRAPHY.items():
        for subregion, codes in subregions.items():
            for code in codes:
                if code in lookup:
                    raise ValueError(f"Duplicate assignment: {code}")
                lookup[code] = {
                    "continent": continent,
                    "subregion": subregion,
                }
    return lookup


def main() -> None:
    db_codes = load_db_codes()
    lookup = build_lookup()

    missing = sorted(db_codes - set(lookup))
    extra = sorted(set(lookup) - db_codes)
    if missing:
        raise SystemExit(f"Missing geography for {len(missing)} DB codes: {', '.join(missing)}")
    if extra:
        print("Warning: geography includes codes not in DB:", ", ".join(extra))

    lines = [
        "/** Auto-generated by scripts/generate_country_geography.py — do not edit by hand. */",
        "",
        "export const CONTINENT_ORDER = [",
        "  'asia',",
        "  'europe',",
        "  'africa',",
        "  'oceania',",
        "  'northAmerica',",
        "  'southAmerica'",
        "]",
        "",
        "export const SUBREGION_ORDER = {",
    ]
    for continent, subregions in GEOGRAPHY.items():
        keys = list(subregions.keys())
        joined = ", ".join(f"'{k}'" for k in keys)
        lines.append(f"  {continent}: [{joined}],")
    lines.append("}")
    lines.append("")
    lines.append("export const ISO3_GEOGRAPHY = {")
    for code in sorted(lookup):
        loc = lookup[code]
        lines.append(
            f"  {code}: {{ continent: '{loc['continent']}', subregion: '{loc['subregion']}' }},"
        )
    lines.append("}")
    lines.append("")
    lines.append("export function getGeography(iso3) {")
    lines.append("  if (!iso3) return null")
    lines.append("  return ISO3_GEOGRAPHY[iso3.trim().toUpperCase()] ?? null")
    lines.append("}")
    lines.append("")

    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {OUT} ({len(lookup)} countries)")


if __name__ == "__main__":
    main()
